FROM python:3.8.13-slim-bullseye

WORKDIR /app

RUN apt-get -y update && apt-get install -y \
  wget \
  wkhtmltopdf

RUN pip install --upgrade setuptools 

COPY requirements.txt .

RUN pip install -r requirements.txt

ADD . . 

ENV POSTGRES=$POSTGRES \
    SQLITE=$SQLITE \
    SERVER_MODE=$SERVER_MODE \
    SERIAL=$SERIAL \
    OPENAI_KEY=$OPENAI_KEY \
    GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID \
    GOOGLE_OAUTH_CLIENT_SECRET=$GOOGLE_OAUTH_CLIENT_SECRET \
    OAUTHLIB_RELAX_TOKEN_SCOPE=$OAUTHLIB_RELAX_TOKEN_SCOPE \
    OAUTHLIB_INSECURE_TRANSPORT=$OAUTHLIB_INSECURE_TRANSPORT \
    GITHUB_OAUTH_CLIENT_SECRET=$GITHUB_OAUTH_CLIENT_SECRET \
    GITHUB_OAUTH_CLIENT_ID=$GITHUB_OAUTH_CLIENT_ID \
    ADMIN_USERNAME=$ADMIN_USERNAME \
    ADMIN_PASSWORD=$ADMIN_PASSWORD \
    ADMIN_EMAIL=$ADMIN_EMAIL \
    IS_ADMIN=$IS_ADMIN \
    DEV_MAIL_SERVER=$DEV_MAIL_SERVER \
    DEV_MAIL_PORT=$DEV_MAIL_PORT \
    DEV_MAIL_USERNAME=$DEV_MAIL_USERNAME \
    DEV_MAIL_PASSWORD=$DEV_MAIL_PASSWORD \
    DEV_SECRET_KEY=$DEV_SECRET_KEY \
    DEV_SENDER_EMAIL=$DEV_SENDER_EMAIL \
    PROD_MAIL_SERVER=$PROD_MAIL_SERVER \
    PROD_MAIL_PORT=$PROD_MAIL_PORT \
    PROD_MAIL_USERNAME=$PROD_MAIL_USERNAME \
    PROD_MAIL_PASSWORD=$PROD_MAIL_PASSWORD \
    PROD_SECRET_KEY=$PROD_SECRET_KEY \
    PROD_SENDER_EMAIL=$PROD_SENDER_EMAIL

RUN cd src && python init.py

CMD gunicorn app:app 